
name: Update Components Submodules

on:
  push:
    branches:
      - central
  pull_request:
    branches:
      - central
  workflow_dispatch:
  workflow_call: # This is a custom event that we will trigger manually

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules
        run: |
          # Only update the "components" submodule, we want to ignore l10n
          current_path=$(pwd)
          submodule_path="$(git config --file .gitmodules --get-regexp path | awk '{ print $2 }' | grep zen-components --color=never)"
          echo "Submodule path: $submodule_path"
          cd $submodule_path
          git checkout main
          git pull
          cd $current_path
        
          git add .
          git commit -m "[skip ci] 📦 Update Submodules!"
          git push


